### ISSUE TITLE
Sync onChange with yup transformations

### ISSUE THREAD

**Issue by alpacaaa** [jquense/react-formal#30]
Hey there,

I find yup transformations to be extremely useful, but the `onChange` handler on Form gets called right away, shouldn't it wait for the schema to be validated?

I created this test to better explain what I'm saying:

```
describe.only('onChange should wait for transformations', () => {

  yup.addMethod(yup.string, 'somemethod', () => 'fixedvalue');


  var change = v => {
   // v equals { name: { last: '', first: 'Jill' } } but is it correct?

    v.should.eql({
      name: {
        first: 'fixedvalue', last: ''
      }
    })
  }

  var schema = yup.object({
    name: yup.object({
      first: yup.string().somemethod(),
      last:  yup.string().default('')
    })
  })


  var inst = $(
      <Form schema={schema} defaultValue={schema.default()} onChange={change}>
        <Form.Field name='name.first' className='field'/>
        <Form.Field name='name.last' className='field'/>
      </Form>
    ).render()

  inst.first('.field').trigger('change', { target: { value: 'Jill' } })
});
```

Is this intended behaviour? Thanks for the help!

**Comment by jquense** [comment]
the current behavior is intended. the problem is that onChange in React is a signal to change the value vs an alert that the value changed. if we validate the value before it's set back on the form, we could be validating a value that isn't ultimately set to the form. for example I could just not flush a change back to form, effectively preventing or reseting it. if the form already validated the value it would display an error for value that doesn't actually exist. so instead the value is validating when it actually changes on the form I. e. componentWillReceiveProps. 

I admit that this is a bit annoying however since schema are independent from the form you can just cast the object yourself in onChange if that's helpful to you.

**Comment by alpacaaa** [comment]
Makes sense. Closing this, thanks a lot for your support.
