### ISSUE TITLE
form value does not update field value when updating store

### ISSUE THREAD

**Issue by jamesjjk** [jquense/react-formal#31]
When using the form in a controlled manner the field value prop(s) are not updated when the form value is updated from a store.. It looks like it is implemented to work on componentWillMount but not on componentWillReceiveProps..

**Comment by jamesjjk** [comment]
I noticed that you can only use a mutable state as a value for a form not an immutable  prop passed from a store..

**Comment by jquense** [comment]
> I noticed that you can only use a mutable state as a value for a form not an immutable prop passed from a store

I'm not sure what you mean by this...the opposite is true, the form is built on the assumption that value is immutable so only updates when the `value` changes.

I am not sure waht flux thing or version you are using but we use react-formal just fine with redux in a bunch of apps, so if something is not updating it may be due to your store not actually returning an updated or new value.

**Comment by jamesjjk** [comment]
@jquense I'm using react formal in a fluxible setup. The store is certainly updating, and thus the form value is also being updated, but the value prop of any of the custom form elements lets say a selector is not updating.. however if I update a state and use the state as an input the value does update which is a very strange behaviour..

**Comment by jamesjjk** [comment]
Ok I cloned the object from the store and used that as the prop value, it is no longer an immutable object but mutable and it seems to work..
