### ISSUE TITLE
Autofill does not change value

### ISSUE THREAD

**Issue by Maxoos** [jquense/react-formal#40]
Looks like the autofill feature in Safari isn't actually picked up in the field value. For instance, if I write "te" and safari autofills it to "test", on submission only "te" will be set.

Thanks!

**Comment by jquense** [comment]
Change events fire on react's onChange, if React isn't hearing Safari's autofill then I'm pretty sure it a bug in React, and since its safari i'm guessing is some sort of intentional derivation from the behavior of every other browser because Apple.

In any case, unfortunately I'm not sure there is anything I can do to fix it, especially sine I don't have anything with safari to test on :/ but if there is something obvious i'm missing i'll take PR. thanks!
