### ISSUE TITLE
Work with Immutable.js structures

### ISSUE THREAD

**Issue by darkadept** [jquense/react-formal#41]
I'd love to have the ability to pass Immutable.js structures to React Formal. Is this feasible?

I don't mind seeing if I could add this myself, but I'm not quite sure where to start?

**Comment by auschmann** [comment]
I used Seamless-immutable in concjunction with react formal
and everything worked well. To day i did an update of react-formal
and i see that react formal now mutates my value object.

Did react-formal always make a copy of the value object? 
Otherwise i can not explain why it worked before.

I updated from 0.16.0 to 0.18.5

**Comment by jquense** [comment]
Where do we mutate the value object? we definitely shouldn't be doing that if so that would be a bug :)

**Comment by auschmann** [comment]
Sorry for the late response, in fact the error was on my side.
