### ISSUE TITLE
Apply invalid-field className to Form.Field's parent

### ISSUE THREAD

**Issue by web2style** [jquense/react-formal#54]
I have the following HTML structure for my form:

```
<label className="bb">Subject*<Form.Message for="subject"/>
    <Form.Field name="subject"/>
</label>
```

Is there a way to apply `invalid-field` className to `label` instead of `Form.Field` itself?

**Comment by dannief** [comment]
You might have figured this out already but you can do this manually. If you register a handler to the Forms, onError event you get the validation errors object. From there you can store the errors object in you component state and use it do whatever you need to do based on the errors returned

e.g. 

```
<label className={this.state.errors.subject ? 'invalid-field': ''}>Subject*<Form.Message for="subject"/>
    <Form.Field name="subject"/>
</label>
```

This way you can add whatever class you want. Note that this works because the `this.state.errors.subject` will be falsy if there are no validation errors for the subject field.

Hope this helps.
