### ISSUE TITLE
Force validation

### ISSUE THREAD

**Issue by kirillkostko** [jquense/react-formal#61]
Hello @jquense ,

First of all thank you for react-formal. I want to ask you if there a way to force validation after I programmatically set values to the form. Below I added an example of a component where a click on `Set values` buttons set values to the form.

```javascript
class App extends React.Component {
  schema = {
    firstName: yup.string().required('Please enter first name')
  }

  state = {
    value: {}
  }

  componentWillMount() {
    const schema = yup.object(this.schema);
    this.schema = schema;
  }

  formChange(formValue) {
    const value = Object.assign({}, this.state.value, formValue);
    this.setState({ value });
  }

  formSubmit(formValue) {
    console.log('Form submitted', this, formValue);
  }

  setValue() {
    const value = Object.assign({}, this.state.value, { firstName: 'asd' });
    this.setState({ value });
  }

  render() {
    return (
        <div>
          <Form
            schema={this.schema}
            value={this.state.value}
            onChange={this.formChange.bind(this)}
          >
            <div>
              <Form.Field name="firstName" />
              <Form.Message for="firstName" component="div" />
            </div>
            <div>
              <Form.Button type="submit">Submit</Form.Button>
            </div>
          </Form>
          <button onClick={this.setValue.bind(this)}>Set values</button>
        </div>
      );
  }
};

export default App;
```

**Comment by maullerz** [comment]
you always can validate any values by this way
`this.schema.validate(this.state.value)`

**Comment by kirillkostko** [comment]
@maullerz thank you for your reply. I know about that feature. But I want to force the whole life-cycle on my `Form.Field` component when I set a new value.

**Comment by jquense** [comment]
@kirillkostko set a ref on the Form, and call `this.refs.form.submit()` which will trigger validation.

**Comment by kirillkostko** [comment]
@jquense it will trigger validation for the whole form, not for the only field.

**Comment by jquense** [comment]
yup. There isn't any specific api for programmatically triggering validation for a single input, apart from using the schema directly and controlling the form errors to display them. I am of course not familiar with your use-case but generally trying to programmatically set values that also need validation is a design flaw. The goal is to validate input, if you are setting the values yourself, then why not set valid values, and what would be the point of showing an error message to a user for a value they can't control?

Otherwise you may want to mess around with custom Field types (or get creative with the API). In you example you _could_ do this:

```js
<Form.Field
  name='firstName' 
  type="button"
  events='onClick'
  mapValue={() => ({ firstName: 'asd' })}
/>
```

That is a little awkward because it requires a single `name` (that may change in the future) but you can change many values

**Comment by jquense** [comment]
hmm I'm just now actually looking at what I expose on the Form. It looks like I do provide a programmatic api.

`this.refs.form.validate(['firstName', 'lastName'])`

**Comment by kirillkostko** [comment]
@jquense got it. My point is to show not only error messages, but success messages too. Thank you for your help, I'll check your suggestions.
