### ISSUE TITLE
Infinite loop with errors

### ISSUE THREAD

**Issue by miracle2k** [jquense/react-formal#69]
My code is like the example given in the docs here: http://jquense.github.io/react-formal/docs/#/api/form?_k=9xr2o6

```jsx
<Form schema={modelSchema}
  defaultValue={modelSchema.default()}
  errors={this.state ? this.state.errors : {}}
  onError={errors => {
    if( errors.dateOfBirth )
      errors.dateOfBirth = 'hijacked!'
    this.setState({ errors })
  }}>

  <Form.Field name='dateOfBirth'/>
  <Form.Message for='dateOfBirth'/>

  <Form.Button type='submit'>Submit</Form.Button>
</Form>
```

What ends up happening is that the ``onError`` callback is continuously executed even lacking any user input, as long as an error occurs. The reason for this seems to be that this check in ``componentWillReceiveProps`` is disabled:

https://github.com/jquense/react-formal/blob/master/src/Form.jsx#L355

Side-question: I need to know if the form is valid. Is it the intended API that ``onError`` gives the final validation result, and I check that the errors object is empty? I am asking because the naming and docs focus only on "errors occurring". I want to disable a save button as soon as the validation fails.

**Comment by jquense** [comment]
Not sure what might be causing a loop...its not occurring on the docs site. The spot you pointed it is correct, that check shouldn't run, and the code that it calls won't do anything if there are no pending validations, so that wouldn't be the cause of it.

If you want to know if the form is valid at any given moment then yes, control `errors` and check if its empty. Generally though you probably won't need to do that often, if you are using the Form.Buttons, to submit as they won't trigger `onSubmit` unless the form is valid.

**Comment by miracle2k** [comment]
I looked into it some  more. Apparently I must not declare the yum schema within ``render()``. If I do that, the form will require the validations on every render.

**Comment by jquense** [comment]
that's a caveat I should document, but yes, schema are immutable so if the change the assumption is that it should sync up the state with the new schema...not sure that is still a good idea tho.

in anycase you don't want to define schema in a render, thats gonna be more expensive then necessary :)
