### ISSUE TITLE
Errors are not propagated for extra `.test` methods

### ISSUE THREAD

**Issue by kompot** [jquense/react-formal#8]
Given this schema
```javascript
const schema = yup.object({
  password: yup.object({
    first: yup.string().required('Pass1'),
    second: yup.string().required('Pass2')
  }).test('samePasswords', 'Pass1 does not equal Pass2', async function (value) {
    await Promise.delay(50);
    return value.first && value.first === value.second;
  })
});
```
and this form
```javascript
<Form schema={schema} onError={(errors) => console.log(errors)}>
  <Form.Field name='password.first' type='text' />
  <Form.Field name='password.second' type='text' />
</Form
```
console logs errors for `password.first` and `password.second` but not for `password` in case strings are not equal. Just empty object.

Also if I do add `onChange={this.onFormChange}` to the `<Form>` and, given this implementaion of `onFormChange` 

```javascript
onFormChange = async (v) => {
  try {
    const value = await schema.validate(v, {abortEarly: true});
  } catch (err) {
    console.log(err);
  }
}
```
console logs all the required errors, including two strings not being equal.

Thanks for your efforts — really sane approach to forms.

**Comment by jquense** [comment]
So this is a bit of a tough problem and I am not completely satisfied with the current solutions, but there are a few approaches you can use to handle a situation like this. The issue is that formas will _only_ validate against paths that have inputs (with a `name`), In this case `password` doesn't have a corresponding input so nothing happens.

You use the `alsoValidates` prop to tell the fields to also trigger validation for the `password` path. this is a bit weird because it will retrigger validation on both `password.first` and `password.second` but it works

```js
<Form.Field name='password.first' type='text' alsoValidates='password'/>
```
This works ok unless `password` has additional properties with validations, in which case they too would be validated, although not a problem here.

The second approach is to push the validation down into `first` and `second` fields. like this:

```js
const samePassword = {
  name: 'samePasswords',
  message: 'Pass1 does not equal Pass2',
  test: function (value, path, context){
    return value == null || context.first === context.second;
  }
}

const schema = yup.object({
  password: yup.object({
    first: yup.string().required('Pass1') .test(samePassword )
    second: yup.string().required('Pass2').test(samePassword )
  })
});
```

The third option is just to manually validate against the schema whenever you feel is appropriate and pass the errors back to form using the `errors` prop. If there is a `Message` component for `password` it will show up.

**Comment by kompot** [comment]
Great, thanks, this will do it in my case. Closing.
