### ISSUE TITLE
[WIP] React-Formal-Examples

### ISSUE THREAD

**Issue by maullerz** [jquense/react-formal#92]
I really like **react-formal**. And i don`t like other form libraries (such redux-form), that i think too complicated and overengineered.
I am use it in all of my projects and trying to popularize this library to others.
But i know that many people confused how to quick start with react-formal.
So i decide to make some code examples to show "how".

https://github.com/maullerz/react-formal-examples

Any critics, advices, proposals and contributions are welcome!

**Comment by kompot** [comment]
I think a working demo on a web site like react-formal-examples.github.io is crucial for such things.

**Comment by jquense** [comment]
hi folks, I'm always glad to have folks work on examples. Unfortunately I don't have a ton of time to read through them though, but I'm glad you enjoy the library. I'd also totally appreciate PR's to the documentation to fill gaps you see :) 

I also agree that working demos are crucial, which is why the docs site tries to provide working examples whenever feasible.

**Comment by maullerz** [comment]
> web site like react-formal-examples.github.io
agree, this is first priority, wip (unfortunately, dont have too much time)
